### ISSUE TITLE
the thing

### ISSUE THREAD

**Issue by homeless1337** [justvmexit/keyauth-expose#4]
https://cdn.discordapp.com/attachments/841340570529038346/907090178806542366/68747470733a2f2f692e696d6775722e636f6d2f7a353067344b362e706e67.png

i dont even own chea.to domain so how can i upload cauth files and how am i pasting cauth if i was not the one who uploaded it

**Comment by Xenia0** [comment]
shut up homeless go back to pasting for your pro developer friend.

@justvmexit  add me in discord, vmread#0399

**Comment by McIvanX** [comment]
Zerax entered da chat XD

**Comment by Xenia0** [comment]
shut up fortnite paster, go back to paste.

**Comment by AustralianDeveloper** [comment]
> i dont even own chea.to domain so how can i upload cauth files and how am i pasting cauth if i was not the one who uploaded it

> shut up homeless go back to pasting for your pro developer friend.

Yo Omani boi whatever your new alt is called now, I am hosting cAuth paste simply as homeless and I were testing stuff out on my server and basic code that just needed a basic auth to test, it wasn't homeless that's hosting.
Nor do I use cAuth in any of my software it wasn't for my liking to be a great base - in fact once my university work for the semester is done, I am doing a full recode of all my code which I explained on my Discord server, as I plan to go big in 2022 and don't need shitty half-written crap.

Also homeless hasn't done any developmental work for me for a few months, he did the old Fortnite cheat which I currently do not sell and will be rewriting my own cheats to sell (I was selling my external but quickly pulled sales as I wanted to recode). Probably won't have any cheats out till 2022, I would like to do my recode work first and get a new store/panel, web loader + build server up and running.

**Comment by H4xton** [comment]
Instruction unclear brain stuck in lawn mover

**Comment by justvmexit** [comment]
> shut up homeless go back to pasting for your pro developer friend.
> 
> @justvmexit add me in discord, vmread#399

Not really a valid discord username and tag :/

**Comment by homeless1337** [comment]
> shut up homeless go back to pasting for your pro developer friend.
> 
> @justvmexit add me in discord, vmread#399

you go back to sucking viper devs dick and go back to gujrat in india

**Comment by homeless1337** [comment]
i can kill your ego and release ur full dox rn but im nice so thank me.

**Comment by homeless1337** [comment]
also tell Brajesh kumar he should take care of his child aryan kumar

**Comment by homeless1337** [comment]
Ennui#7935 and CODEX#8320 ur alts

**Comment by Xenia0** [comment]
> i can kill your ego and release ur full dox rn but im nice so thank me.

go ahead, idk who brajesh kumar is and how I am in gujrat, india but ok.

> > shut up homeless go back to pasting for your pro developer friend.
> > @justvmexit add me in discord, vmread#399
> 
> Not really a valid discord username and tag :/

vmread#0399
dont know why discord removed the 0 when I pressed the copy button.

**Comment by Xenia0** [comment]
> > shut up homeless go back to pasting for your pro developer friend.
> > @justvmexit add me in discord, vmread#399
> 
> you go back to sucking viper devs dick and go back to gujrat in india

what?

**Comment by McIvanX** [comment]
ur scared

**Comment by H4xton** [comment]
instruction unclear penis stuck in toaster // Issue Closed
